# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release Dry-Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    # Only release on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main

    runs-on: ubuntu-latest
    # Waits for test jobs for each Node.js version to complete
    needs: [build]

    steps:
    - name: Checkout
    uses: actions/checkout@v2

    - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
      node-version: [14.x]

    - name: Install
    run: npm ci

    - name: Release
    run: npx semantic-release --dry-run
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


  
